export const csp_directives = {
	'default-src': ["'self'"],
	'script-src': [
		"'self'",
		"'unsafe-inline'",
		"'unsafe-eval'",
		"'wasm-unsafe-eval'",
		'https://cdn.usefathom.com',
	],
	'script-src-elem': [
		"'self'",
		"'unsafe-inline'",
		'https://cdn.usefathom.com',
	],
	'style-src': ["'self'", "'unsafe-inline'"],
	'img-src': ["'self'", 'data:', 'https://cdn.usefathom.com'],
	'font-src': ["'self'", 'data:'],
	'connect-src': [
		"'self'",
		'https://api.usefathom.com',
		'https://*.usefathom.com',
	],
	'frame-src': ["'none'"],
	'object-src': ["'none'"],
	'base-uri': ["'self'"],
	'form-action': ["'self'"],
	'frame-ancestors': ["'none'"],
	'upgrade-insecure-requests': [],
	'report-uri': ['/api/csp-report'],
} as const;
